name: contact_book
channels:
  - conda
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - isort=5.9.3
  - libffi
  - openssl=1.1.1
  - pandas=1.3.5
  - pip=21.2.4
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - python=3.9.7
  - setuptools=58.0.4
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
